services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qc\QcBePageLanguage\:
    resource: '../Classes/*'

  Qc\QcBePageLanguage\Domain\Repository\BackendUserRepository:
    public: true
